# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: cbq

archives:
  - formats: [ "tar.gz" ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md # I should create a README.md or use index.md

brews:
  - name: cbq
    # Repository to push the tap formula to
    repository:
      owner: vibe-coding
      name: cbq
    directory: .
    commit_author:
      name: cbq-bot
      email: cbq-bot@vibe-coding.com
    homepage: "https://github.com/vibe-coding/cbq"
    description: "A clipboard manager that works like a stack or queue"
    license: "MIT"
    install: |
      bin.install "cbq"
    test: |
      system "#{bin}/cbq --version"

release:
  # Using default auto-detection for owner/name to avoid 404 if repo is renamed
  prerelease: auto

snapshot:
  version_template: "{{ incpatch .Version }}-next"
